import {
  ArrowLeftRight,
  ArrowUpDown,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CloudOff,
  Code,
  Ellipsis,
  Eye,
  EyeOff,
  Inbox,
  Info,
  LoaderCircle,
  Lock,
  MinusCircle,
  Pencil,
  PlusCircle,
  RefreshCcw,
  Shuffle,
  TriangleAlert,
  X,
  Settings,
} from 'lucide-react';

export const Icons = {
  alert: TriangleAlert,
  arrowUpDown: ArrowUpDown,
  check: CheckCircle,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  cloudOff: CloudOff,
  code: Code,
  edit: Pencil,
  eye: Eye,
  eyeOff: EyeOff,
  gear: Settings,
  inbox: Inbox,
  info: Info,
  loader: LoaderCircle,
  lock: Lock,
  minus: MinusCircle,
  more: Ellipsis,
  plus: PlusCircle,
  pool: Eye,
  refresh: RefreshCcw,
  shuffle: Shuffle,
  switch: ArrowLeftRight,
  x: X,
};
