name: Deploy Code

on:
  push:
    branches:
      - master

env:
  node_version: 18.19.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Install dependencies
        run: pnpm install
        env:
          CI: true
      - name: Production build
        run: pnpm build
        env:
          CI: false
